version: '3'
services:

  hdtapps-framework:
    build: .
    image: trade4chor/hdtapps-framework:latest
    ports:
      - "8080:8080"
    environment:
      - DOCKER_HOST=http://192.168.109.132:2376
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - '.:/home/dummy/app'
    networks:
      - hdtapps
    depends_on:
      - mongodb
      - celery-worker
      - redis
  
  mongodb:
    image: 'mongo:3.7'
    volumes:
      - 'mongodata:/data'
    ports:
      - '27017:27017'
    networks:
      - hdtapps
  
  celery-worker:
    build: .
    image: trade4chor/hdtapps-framework:latest
    command: su dummy -c 'celery worker -A celery_worker.celery --loglevel=info'
    environment:
      - DOCKER_HOST=http://192.168.109.132:2376
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - '.:/home/dummy/app'
    depends_on:
      - mongodb
      - redis
    networks:
      - hdtapps
  
  redis:
    image: 'redis:alpine'
    volumes:
      - 'redisdata:/data'
    ports:
      - '6379:6379'
    networks:
      - hdtapps
    

networks:
  hdtapps:
    driver: bridge

volumes:
  redisdata:
  mongodata:
